# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import Identity


def set_name(name: str):
	name = name
	SpacetimeDBClient.instance._reducer_call("set_name", name)

def register_on_set_name(callback: Callable[[Identity, str, str, str], None]):
	SpacetimeDBClient.instance._register_reducer("set_name", callback)

def _decode_args(data):
	return [str(data[0])]
