# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from network_manager import NetworkManager

def create_player(name, description):
	NetworkManager.instance.reducer_call("create_player", name, description)
