# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from network_manager import NetworkManager


def create_player(name: str, description: str):
	name = name
	description = description
	NetworkManager.instance.reducer_call("create_player", name, description)

def register_on_create_player(callback: Callable[[str, str], None]):
	if not _check_callback_signature(callback):
		raise ValueError("Callback signature does not match expected arguments")

	NetworkManager.instance.register_reducer("create_player", callback)

def _decode_args(data):
	return [str(data[0]), str(data[1])]

def _check_callback_signature(callback: Callable) -> bool:
	expected_arguments = [bytes, str, str, str, str]
	callback_arguments = callback.__annotations__.values()

	return list(callback_arguments) == expected_arguments
