# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.


class Globals:
	is_table_class = True

	def __init__(self, data):
		self.data = {}
		self.data["id"] = int(data[0])
		self.data["spawnable_entity_id_counter"] = int(data[1])
