# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from client_cache import ClientCache

class Globals:
	is_table_class = True

	@classmethod
	def iter(cls):
		return ClientCache.instance.get_table_cache("Globals").values()

	@classmethod
	def filter_by_id(cls, id):
		return next(iter([column_value for column_value in ClientCache.instance.get_table_cache("Globals").values() if column_value.id == id]), None)

	@classmethod
	def filter_by_spawnable_entity_id_counter(cls, spawnable_entity_id_counter):
		return [column_value for column_value in ClientCache.instance.get_table_cache("Globals").values() if column_value.spawnable_entity_id_counter == spawnable_entity_id_counter]

	def __init__(self, data):
		self.data = {}
		self.data["id"] = int(data[0])
		self.data["spawnable_entity_id_counter"] = int(data[1])

	def __getattr__(self, name):
		return self.data.get(name)
