# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from network_manager import NetworkManager

def go(source_spawnable_entity_id, exit_direction):
	NetworkManager.instance.reducer_call("go", source_spawnable_entity_id, exit_direction)

class ReducerArgs:
	def __init__(self, data):
		self.data = {}
		self.data["source_spawnable_entity_id"] = int(data[0])
		self.data["exit_direction"] = str(data[1])

	def __getattr__(self, name):
		return self.data.get(name)
