# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from client_cache import ClientCache

class Player:
	is_table_class = True

	@classmethod
	def iter(cls):
		return ClientCache.instance.get_table_cache("Player").values()

	@classmethod
	def filter_by_spawnable_entity_id(cls, spawnable_entity_id):
		return next(iter([column_value for column_value in ClientCache.instance.get_table_cache("Player").values() if column_value.spawnable_entity_id == spawnable_entity_id]), None)

	@classmethod
	def filter_by_identity(cls, identity):
		return next(iter([column_value for column_value in ClientCache.instance.get_table_cache("Player").values() if column_value.identity == identity]), None)

	def __init__(self, data):
		self.data = {}
		self.data["spawnable_entity_id"] = int(data[0])
		self.data["identity"] = bytes.fromhex(data[1])

	def __getattr__(self, name):
		return self.data.get(name)
