# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.


class Player:
	is_table_class = True

	def __init__(self, data):
		self.data = {}
		self.data["spawnable_entity_id"] = int(data[0])
		self.data["identity"] = []
