# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from .exit import Exit
from .mobile import Mobile

class Room:
	is_table_class = True

	def __init__(self, data):
		self.data = {}
		self.data["name"] = str(data[0])
		self.data["description"] = str(data[1])
		self.data["exits"] = [Exit(item) for item in data[2]]
		self.data["mob"] = Mobile(data[3]['0']) if '0' in data[3] else None
