# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from client_cache import ClientCache

class RoomChat:
	is_table_class = True

	@classmethod
	def iter(cls):
		return ClientCache.instance.get_table_cache("RoomChat").values()

	@classmethod
	def filter_by_room_id(cls, room_id):
		return next(iter([column_value for column_value in ClientCache.instance.get_table_cache("RoomChat").values() if column_value.room_id == room_id]), None)

	@classmethod
	def filter_by_source_spawnable_entity_id(cls, source_spawnable_entity_id):
		return [column_value for column_value in ClientCache.instance.get_table_cache("RoomChat").values() if column_value.source_spawnable_entity_id == source_spawnable_entity_id]

	@classmethod
	def filter_by_chat_text(cls, chat_text):
		return [column_value for column_value in ClientCache.instance.get_table_cache("RoomChat").values() if column_value.chat_text == chat_text]

	def __init__(self, data):
		self.data = {}
		self.data["room_id"] = str(data[0])
		self.data["source_spawnable_entity_id"] = int(data[1])
		self.data["chat_text"] = str(data[2])

	def __getattr__(self, name):
		return self.data.get(name)
