# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from network_manager import NetworkManager

def sign_out(player_spawnable_entity_id):
	NetworkManager.instance.reducer_call("sign_out", player_spawnable_entity_id)

class ReducerArgs:
	def __init__(self, data):
		self.data = {}
		self.data["player_spawnable_entity_id"] = int(data[0])

	def __getattr__(self, name):
		return self.data.get(name)
