# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable

from spacetimedb_python_sdk.spacetimedb_client import SpacetimeDBClient


def say(source_spawnable_entity_id: int, chat_text: str):
	source_spawnable_entity_id = source_spawnable_entity_id
	chat_text = chat_text
	SpacetimeDBClient.instance._reducer_call("say", source_spawnable_entity_id, chat_text)

def register_on_say(callback: Callable[[bytes, str, str, int, str], None]):
	if not _check_callback_signature(callback):
		raise ValueError("Callback signature does not match expected arguments")

	SpacetimeDBClient.instance._register_reducer("say", callback)

def _decode_args(data):
	return [int(data[0]), str(data[1])]

def _check_callback_signature(callback: Callable) -> bool:
	expected_arguments = [bytes, str, str, int, str]
	callback_arguments = callback.__annotations__.values()

	return list(callback_arguments) == expected_arguments
